### ISSUE TITLE
[Enhencement] Scrow bar too long

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/g-team#36]
Since you put very important information for first time users down to buttom, it is so easy to be ignored. Try to find a place to make them more stand out, may be make the first page lay out in two rows instead of columns.

environment it was encountered in Chrome Version 95.0.4638.69 (Official Build) (arm64)
steps to reproduce: scrolling up and down on the landing page.
expected result: Not that long scrolling
actual result: Important information is on the button of the long scrolling bar.

**Comment by njkpark** [comment]
We can keep this suggestion in mind, most of our layout is designed by choice, but usability should take priority in our design decisions.

**Comment by njkpark** [comment]
After some discussion, we decided that we will not complete this enhancement feature since it is a design alteration that does not align with our designer’s preference. We don’t see a big enough impact in changing our layout.
