### ISSUE TITLE
[Minor] on the organizations page there are multiples of a few of the cards, it is a bit confusing as a user i cant tell if it's glitching or the same thing is there multiple times for a reason

### ISSUE THREAD

**Issue by swaleha6** [info442-aut21/g-team#38]
- [Minor] on the organizations page there are multiples of a few of the cards, it is a bit confusing as a user i cant tell if it's glitching or the same thing is there multiple times for a reason
- Firefox on Windows 10
- on organizations page, selected accounting category and had two of the same result
- expected to have one of each result
- actual result: some results have multiples

**Comment by njkpark** [comment]
Descriptions are displayed when clicking on "learn more". We will incorporate descriptions of the volunteer opportunity on the individual cards in the list.

**Comment by aramos10-1863966** [comment]
resolved
https://github.com/info442-aut21/g-team/commit/bd3418084667cbb3b9f58eb17e927ff2b2d5a664
