### ISSUE TITLE
[Major] Address and close button not loading correctly.

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/g-team#40]
<img width="715" alt="Screen Shot 2021-11-22 at 9 07 30 AM" src="https://user-images.githubusercontent.com/59670580/142904449-fcacc04c-6616-4575-853b-0e39f63ee333.png">
After clicking on the learn more button on the card, the pop up page takes so long to upload the map, but I am not sure if there is anything you can do about this. Besides this, the address was loaded for a second but once the map is loading, it disappers, and so does the close button. So there is no way to go back if those things are not loaded correctly.

environment it was encountered in: Chrome Version 95.0.4638.69 (Official Build) (arm64)
steps to reproduce: Click any of the Learn More on the cards
expected result: More information about the card.
actual result: A really slow loaded map, and a second display of the address, and then it disappears. No way to go back.

**Comment by njkpark** [comment]
https://github.com/info442-aut21/g-team/issues/39
