### ISSUE TITLE
[Minor] Organization details popup doesn't consistently show contact form, map and link to org

### ISSUE THREAD

**Issue by victoriathegr8** [info442-aut21/g-team#41]
Upon clicking the card, the map, title of organization, and contact form don't load all at once. It's difficult to tell exactly which card you clicked on when doing this. 
Chrome v96.0.4664.45 on Windows 10
1. Navigate to organizations tab
2. Click on card
3. Scroll down on card
Expected result: all organization details would load atonce
Actual result: Upon scrolling down, all of the components switch off between loading.

**Comment by ayun6** [comment]
Additional:
Clicking the refresh button leads to page 404 not found.
Clicking the card immediately leads to information disappearing from the card and a red dot appearing
Environment: Chrome 95.0.4638.69 on MacOS Big Sur
Expected: Display of appropriate information
Actual: information disappears
<img width="628" alt="Screen Shot 2021-11-22 at 9 18 39 AM" src="https://user-images.githubusercontent.com/72246542/142906097-9c065ed6-962f-4238-b0f1-ec3c65e0da6b.png">

**Comment by njkpark** [comment]
https://github.com/info442-aut21/g-team/issues/39

**Comment by njkpark** [comment]
> Additional: Clicking the refresh button leads to page 404 not found. Clicking the card immediately leads to information disappearing from the card and a red dot appearing Environment: Chrome 95.0.4638.69 on MacOS Big Sur Expected: Display of appropriate information Actual: information disappears <img alt="Screen Shot 2021-11-22 at 9 18 39 AM" width="628" src="https://user-images.githubusercontent.com/72246542/142906097-9c065ed6-962f-4238-b0f1-ec3c65e0da6b.png">

This issue was already discussed in https://github.com/info442-aut21/g-team/issues/39

**Comment by njkpark** [comment]
This issue is valid but difficult to implement during our sprint, especially because this does not seem like a coding issue. Loading of information may vary between computers and browsers.
