### ISSUE TITLE
[Enhencement] Could make dynamic search

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/g-team#42]
I think you can simply change the onclick to onchange and add some eventpreventdefault and store the original data to make that better! This could also fix the issue of could not displaying original data. 

environment it was encountered in: Chrome Version 95.0.4638.69 (Official Build) (arm64)
steps to reproduce: Search or filter the card
expected result: It is dynamic search.
actual result: It is not dynamic search, has to find the exact matched words.

**Comment by njkpark** [comment]
This is a great enhancement and we'll try to work on this during our sprint! This could be difficult to implement but it would definitely help with showing the original data after using the filter features.

**Comment by joonbot1999** [comment]
resolved
