### ISSUE TITLE
[Minor] Back Button not working after filtering and clicking link

### ISSUE THREAD

**Issue by Vivianngu3** [info442-aut21/g-team#43]
![Screen Shot 2021-11-22 at 9 02 13 AM](https://user-images.githubusercontent.com/62910701/142903889-ed8f0aaa-8f65-4353-b50e-b3c82c72f7e6.png)

Description: After filtering and then clicking the organization link it directs to the page and then when trying to hit back button to the site again, this error shows up and the back to site also did not work.
Encountered: Chrome Version 94.0.4606.81 (Official Build) (x86_64)
Steps to reproduce: 1. Click on 'Organizations' 2. Filter by category 'Advocacy' 3. Click on 'Learn More' 4. Click on 'Link to site' 5. Click back button on browser 6. Click 'Back to site'
Expected Results: To go back to the site after clicking the back button on the browser and the 'Back to site' link
Actual Result: The site did not load back and the error kept showing

**Comment by njkpark** [comment]
Will make the "link to site" popup into a different tab to fix this issue.

**Comment by joonbot1999** [comment]
resolved

**Comment by joonbot1999** [comment]
Cannot put a link that resolved it because it can only be resolved when the build is made, which cannot be committed.

**Comment by joonbot1999** [comment]
https://github.com/info442-aut21/g-team/commit/224af1a1ec91adfeafe45c83c42b94ebd94b3269
