### ISSUE TITLE
[Minor] After search there is no way to go back to original data unless click refresh or submit an empty filter

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/g-team#44]
Once we search or filter something, couldn't display the original data unless I refresh the page or submit an enpty filter.

environment it was encountered in: Chorme Version 95.0.4638.69 (Official Build) (arm64)
steps to reproduce: search/filter the cards
expected result:There is some way to see the original data besides refreshin the page 
actual result: Has to refresh the page or submit an empty filter.

**Comment by manyaj57** [comment]
Description: after searching for organization can not reset the organization page 

Steps to Reproduce:
1. Organization page
2. enter search org criteria
3. click submit button
4. click back arrow on browser or refresh page
Expected: I expected the page to show up without search criteria saved
Actual:the page produced an error
Tested on ChromeVersion 96.0.4664.55 (Official Build) on MacOs Catalina

**Comment by njkpark** [comment]
Will create a "show all orgs" button to get back to the original list of cards.

**Comment by aramos10-1863966** [comment]
Resolved - button is titled 'clear' to reset the form rather than 'show all orgs' because clearing the form is more intuitive
https://github.com/info442-aut21/g-team/commit/dad5e9d496c7cc093f4088c7cddd026f360eeded
