### ISSUE TITLE
[Minor] Map is taking too long to render

### ISSUE THREAD

**Issue by matthewputra** [info442-aut21/g-team#46]
Environment: Google Chrome Version 95.0.4638.69 (Official Build) (x86_64)
Steps to reproduce: In the organization tab, click one of the 'learn more' links and it will show an image of a red dot for a couple of seconds, and then the image will finally get rendered.
Expected result: Image renders in less than 1 second
Actual result: Image renders for more than 1 second

**Comment by njkpark** [comment]
We'll talk to Cheri & Daniel about this!

**Comment by njkpark** [comment]
This issue is deemed to be pretty minor by Daniel, so we won't be fixing this issue - but it could be an issue for later development.
