### ISSUE TITLE
[Enhancement] Additional Filter for Location

### ISSUE THREAD

**Issue by nsnatthapat** [info442-aut21/g-team#47]
Add additional filters for organizations such as Location in order to make finding organizations easier.

Can aid usage for target group

**Comment by njkpark** [comment]
Making a filter for location could be a viable enhancement for our sprint (in fact, we had planned to do this before). Perhaps we can make a new filter for location based on city and/or zipcode.

**Comment by joonbot1999** [comment]
resolved
