### ISSUE TITLE
[Major] Once an organization is selected, Browse Organizations do not show the full list of Organizations

### ISSUE THREAD

**Issue by Skylitmoon** [info442-aut21/g-team#48]
1. Click on Organizations
2. Click on any organization
3. Click About Us
4. Click Browse Organizations at the bottom

Expected result: A list of Organizations
Actual result: The organization that was selected earlier with no way to go back to the organization list. 

When refreshing to try to get to the list of organizations, a 404 error occurs. This was tested on MacOS Monterey and Google Chrome Version 96.0.4664.45.

**Comment by njkpark** [comment]
https://github.com/info442-aut21/g-team/issues/44
