### ISSUE TITLE
[Major] App crashes after refreshing

### ISSUE THREAD

**Issue by matthewputra** [info442-aut21/g-team#49]
Environment: Google Chrome Version 95.0.4638.69 (Official Build) (x86_64)
Steps to reproduce: From the main page, click the "Organizations" tab on the top and then refresh the site.
Expected result: app refresh to the "organization" page
Actual result: app crashes
Netlify error message: 
Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

 Back to our site

If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's "page not found" support guide for troubleshooting tips.

**Comment by njkpark** [comment]
Found a possible solution, definitely more of a netlify issue. We'll try working on this during our sprint.

**Comment by joonbot1999** [comment]
resolved

**Comment by joonbot1999** [comment]
Cannot put a link that resolved it because it can only be resolved when the build is made, which cannot be committed.
