### ISSUE TITLE
[Feature Request] Add some sort of images below each organization 

### ISSUE THREAD

**Issue by naishg** [info442-aut21/g-team#51]
Adding an image will better help to visualize and differentiate the different organizations.

**Comment by njkpark** [comment]
Adding unique images for the organizations could be difficult, but we may be able to add images to cards based on their category.

**Comment by joonbot1999** [comment]
resolved

**Comment by joonbot1999** [comment]
https://github.com/info442-aut21/g-team/commit/1507a3a4755e4772f02cd2888efe27208a712112
