### ISSUE TITLE
[Minor]The organization of the cards

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/g-team#53]
Description: The cards seem to be organized with a 3 per row format for the first two rows which does not continue on the third row.
Expected: The cards show up as 3 per row starting from right side of the page.
Actual: The third row has only one card aligned at the centre.
<img width="1440" alt="Screen Shot 2021-11-22 at 9 45 32 AM" src="https://user-images.githubusercontent.com/56050100/142909939-83577630-fb80-40a5-a5ff-2203a58b5067.png">

Tested on Chrome Version 96.0.4664.55 (Official Build) on MacOs Catalina.

**Comment by njkpark** [comment]
This was a design choice, so we will not be fixing this during our sprint.

**Comment by cherimarie** [comment]
If this is a "wontfix", it can be closed.
