### ISSUE TITLE
[Minor]The organizations page is not refreshed

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/g-team#54]
Description: When I go back and forth from the home to organizations, the search results are not refreshed, Once I refresh the page an error shows up that says the page is broken.
Expected: Once I move to a different tab, the filters should be refreshed.
Actual: Does not refresh/go back to the original data,gets broken If manually refreshed it
Tested on Chrome Version 96.0.4664.55 (Official Build) on MacOs Catalina.

**Comment by njkpark** [comment]
Going back and forth from home to organizations, we wanted to make the search results stay the same in case the user wants to go back to their filtered list of cards. The refresh issue has already been discussed: https://github.com/info442-aut21/g-team/issues/49
