### ISSUE TITLE
[minor] unable to search for an org by keyword

### ISSUE THREAD

**Issue by manyaj57** [info442-aut21/g-team#55]
Description: searching by keyword always shows "search not found"

Steps to Reproduce:

1. Go to organization page
2. Type a key word into search bar
3. Apply search either by pressing "submit " button
Expected: I expected it to show up search results for the keywords.
Actual:the page produces search not found
Tested on ChromeVersion 96.0.4664.55 (Official Build) on MacOs Catalina

**Comment by njkpark** [comment]
Duplicate: https://github.com/info442-aut21/g-team/issues/50

**Comment by cherimarie** [comment]
For development purposes, I can see that this is a duplicate of #50, but for @manyaj57 's phase 7 grade, I'm not counting this as a duplicate.
