### ISSUE TITLE
[Minor] Exit/Back Button When Selecting "Learn More" for an Organization is Out of Visibility (no way to exit out of card except through submission)

### ISSUE THREAD

**Issue by julianedelossantos** [info442-aut21/g-team#57]
On a full browser window, you can just barely see the exit button for the pop-up window at the top right. If you align your mouse correctly, you are able to successfully click it and back out of the window, but it's not in complete view and there is no visible symbol indicating that it is an exit button to begin with. When reducing the width of the window as much as possible, you aren't able to see the exit button at all. This is probably just an alignment issue with the exit button in those "learn more" pop-up windows.

Environment: Windows 11 - Brave Browser: Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

To reproduce this issue:
Home page > Organizations > Learn more on any organization

The result I was expecting was to have some kind of option available and visible at the top right-hand corner to be able to back out of that pop-up without needing to have a submission. Additionally, you might want to consider allowing users to simply hit the escape button or click out of the pop-up in order to exit.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/72470963/143041126-21822934-2fae-4b67-9f54-3434135d9bbf.png">

**Comment by njkpark** [comment]
This issue is definitely viable to complete during our sprint and it seems like it's a responsiveness issue.

**Comment by njkpark** [comment]
This was a design decision. Some people may want to stay anonymous but we require them to provide their email to contact the organizations.
