### ISSUE TITLE
[Feature Request] About Us page includes information about the development team

### ISSUE THREAD

**Issue by julianedelossantos** [info442-aut21/g-team#58]
Most of the other teams have information that showcases developers under an About Us page as well as the link to the GitHub repository. Perhaps consider making cards underneath a section labeled "Our Team" that describe your respective roles as well as links to some kind of contact such as a LinkedIn. The formatting should be consistent with the rest of the page of course.

**Comment by njkpark** [comment]
We think this is a great idea to implement - we got the chance to see others' projects and really liked the personal touch of adding our team's information.

**Comment by joonbot1999** [comment]
resolved

**Comment by joonbot1999** [comment]
https://github.com/info442-aut21/g-team/commit/eb66e71286e141307823a988f5cfb563b1891d43
