### ISSUE TITLE
[Minor] Contact the Organization Form

### ISSUE THREAD

**Issue by vanessasgh** [info442-aut21/g-team#59]
When you search for an organization and click on one of them, if you do not fill your name in but only your email and content, it allows you to submit the form. I do not know if this was intentional but if it is a form, with those text boxes, I would assume that you will need to fill in everything unless you indicate it with a "*must fill in" writing somewhere.

**Comment by njkpark** [comment]
This was not intentional! All fields must be filled out before submitting the form.

**Comment by joonbot1999** [comment]
resolved

**Comment by joonbot1999** [comment]
https://github.com/info442-aut21/g-team/commit/cd7452913ae246248ea0c2074123e83e1e36054e
