### ISSUE TITLE
[Minor] Close button is hiding on pop up

### ISSUE THREAD

**Issue by vanessasgh** [info442-aut21/g-team#60]
When you search and select an organization, there's a pop up that shows more details about it. The "x" / close button for the pop up seem to be shifted upwards and hard to be seen. Since this is the only way to close that pop up, I think it would be better to make it not out of bounds and that it should be a little bit more visible to help the users out. This will definitely improve usability and navigation.
![image](https://user-images.githubusercontent.com/63211951/143177146-0d541f0f-485a-4c7b-a704-35c03c44b702.png)

**Comment by njkpark** [comment]
Duplicate: https://github.com/info442-aut21/g-team/issues/57
