### ISSUE TITLE
[Enhancement] Search Bar Limit

### ISSUE THREAD

**Issue by vanessasgh** [info442-aut21/g-team#62]
I don't think there's any text limit(characters) for the search bar. If a user accidentally copy pasted a lot of words, it would just all copy onto the text input. It is not completely necessary but it might a nice UI design to implement a certain text limit for the search bar, especially when most of the organizations does not reach more then 2 or 3 words.

**Comment by njkpark** [comment]
Definitely will consider this! Especially for our form fields as well.

**Comment by joonbot1999** [comment]
resolved

**Comment by joonbot1999** [comment]
https://github.com/info442-aut21/g-team/commit/1507a3a4755e4772f02cd2888efe27208a712112
